"use client";

import { useMemo, useState } from "react";
import type { Scenario } from "@cel/types";
import { api, type RetrievalResult } from "@/lib/api";
import { useAsync } from "@/lib/useAsync";
import { useWorkspace } from "@/components/WorkspaceProvider";
import { Button } from "@/components/Button";
import { EmptyState } from "@/components/EmptyState";
import { ErrorState, LoadingState } from "@/components/States";
import { PageHeader } from "@/components/PageHeader";
import { TrustCopy } from "@/components/TrustCopy";

const SIM_TRUST = [
  "Simulated from permission metadata — deterministic, no document content read.",
  "This shows what M365 Copilot, grounded on a user's access, could surface to them.",
  "Sensitivity is computed by the rule engine; nothing here is generated by an LLM.",
];

/** Sentinel for the default persona (no explicit actorId sent to the API). */
const DEFAULT_ACTOR = "__default__";

/** A thin sensitivity bar, 0..1 mapped to a width + severity tint. */
function SensitivityBar({ value }: { value: number }) {
  const pct = Math.round(Math.min(1, Math.max(0, value)) * 100);
  const tint =
    value >= 0.9 ? "bg-severity-critical" : value >= 0.6 ? "bg-severity-high" : value >= 0.3 ? "bg-severity-medium" : "bg-severity-low";
  return (
    <div className="flex items-center gap-2">
      <div className="h-2 w-28 overflow-hidden rounded-full bg-surface-muted">
        <div className={`h-full rounded-full ${tint}`} style={{ width: `${pct}%` }} aria-hidden />
      </div>
      <span className="w-9 text-right text-xs tabular-nums text-ink-soft">{(value).toFixed(2)}</span>
    </div>
  );
}

export default function CopilotSimPage() {
  const { dataVersion, runAssessment, scanning } = useWorkspace();
  const [actor, setActor] = useState<string>(DEFAULT_ACTOR);

  // Scenarios give us selectable actor personas (those with an actorPrincipalId).
  const { data: scenarios } = useAsync<Scenario[]>(() => api.listScenarios(), [dataVersion]);

  const actorOptions = useMemo(() => {
    const seen = new Set<string>();
    const opts: { id: string; label: string }[] = [];
    for (const s of scenarios ?? []) {
      if (s.actorPrincipalId && !seen.has(s.actorPrincipalId)) {
        seen.add(s.actorPrincipalId);
        opts.push({ id: s.actorPrincipalId, label: `${s.title} (${s.actorPrincipalId})` });
      }
    }
    return opts;
  }, [scenarios]);

  const { data, loading, error, reload } = useAsync<RetrievalResult>(
    () => api.getRetrieval(actor === DEFAULT_ACTOR ? undefined : actor),
    [dataVersion, actor],
  );

  const fieldClass =
    "rounded-md border border-surface-border bg-surface px-2.5 py-1.5 text-sm text-ink focus:outline-none focus:ring-2 focus:ring-brand/30";

  return (
    <>
      <PageHeader
        title="Copilot simulation"
        description="What M365 Copilot, grounded on what a user can access, could surface to them — ranked by sensitivity. The product thesis made concrete."
        actions={
          <label className="flex items-center gap-2 text-xs font-medium text-ink-soft">
            Acting as
            <select className={fieldClass} value={actor} onChange={(e) => setActor(e.target.value)}>
              <option value={DEFAULT_ACTOR}>Default persona (normal employee)</option>
              {actorOptions.map((opt) => (
                <option key={opt.id} value={opt.id}>
                  {opt.label}
                </option>
              ))}
            </select>
          </label>
        }
      />

      {loading ? (
        <LoadingState label="Simulating retrieval…" />
      ) : error ? (
        error.toLowerCase().includes("no connection") ? (
          <EmptyState
            title="No tenant connected yet"
            description="Run an exposure assessment to seed the demo tenant, then simulate what Copilot could surface."
            action={
              <Button onClick={() => void runAssessment()} busy={scanning}>
                Run exposure assessment
              </Button>
            }
          />
        ) : (
          <ErrorState message={error} onRetry={reload} />
        )
      ) : !data ? null : (
        <div className="space-y-5">
          <div className="rounded-lg border border-surface-border bg-surface p-5">
            <p className="text-sm text-ink-soft">
              Grounded on <span className="font-semibold text-ink">{data.actorName}</span>&apos;s access, Copilot could
              surface <span className="font-semibold text-ink">{data.items.length}</span> sensitive item
              {data.items.length === 1 ? "" : "s"} — ranked by computed sensitivity.
            </p>
          </div>

          {data.items.length === 0 ? (
            <EmptyState
              title="Nothing sensitive reachable"
              description="This actor cannot reach any sensitive files through current permissions, groups, or links."
            />
          ) : (
            <div className="overflow-hidden rounded-lg border border-surface-border">
              <table className="w-full border-collapse text-sm">
                <thead className="bg-surface-subtle text-left text-xs uppercase tracking-wide text-ink-faint">
                  <tr>
                    <th className="px-4 py-2 font-medium">Resource</th>
                    <th className="px-4 py-2 font-medium">Sensitivity</th>
                    <th className="px-4 py-2 font-medium">Reachable via</th>
                    <th className="px-4 py-2 font-medium">Top signals</th>
                  </tr>
                </thead>
                <tbody>
                  {data.items.map((item) => (
                    <tr key={item.resourceId} className="border-t border-surface-border">
                      <td className="px-4 py-3">
                        <div className="font-medium text-ink">{item.name}</div>
                        <div className="font-mono text-xs text-ink-faint">{item.resourceId}</div>
                      </td>
                      <td className="px-4 py-3">
                        <SensitivityBar value={item.sensitivity} />
                      </td>
                      <td className="px-4 py-3">
                        <span className="rounded bg-surface-muted px-2 py-0.5 text-xs text-ink-soft">{item.via}</span>
                      </td>
                      <td className="px-4 py-3">
                        {item.topSignals.length > 0 ? (
                          <div className="flex flex-wrap gap-1">
                            {item.topSignals.slice(0, 4).map((sig) => (
                              <span key={sig} className="rounded bg-surface-subtle px-1.5 py-0.5 text-xs text-ink-soft">
                                {sig}
                              </span>
                            ))}
                          </div>
                        ) : (
                          <span className="text-ink-faint">—</span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          <TrustCopy lines={SIM_TRUST} />
        </div>
      )}
    </>
  );
}
