"use client";

import { useMemo, useState } from "react";
import type { Scenario } from "@cel/types";
import { api, ApiError, type CopilotAnswer } from "@/lib/api";
import { useAsync } from "@/lib/useAsync";
import { useWorkspace } from "@/components/WorkspaceProvider";
import { AlertIcon } from "@/components/icons";
import { Button } from "@/components/Button";
import { EmptyState } from "@/components/EmptyState";
import { ErrorState } from "@/components/States";
import { PageHeader } from "@/components/PageHeader";
import { TrustCopy } from "@/components/TrustCopy";

const SIM_TRUST = [
  "Simulated from permission metadata — deterministic, no document content is read.",
  "Citations are the sensitive documents this user can already reach — not generated by an LLM.",
];

/** Sentinel for the default persona (no explicit actorId sent to the API). */
const DEFAULT_ACTOR = "__default__";

/** Suggested prompts shown as one-click chips. */
const SUGGESTIONS = [
  "Summarize our 2026 compensation plan",
  "What's in the acquisition strategy?",
  "Show me customer contracts",
  "Any security incident notes?",
];

/**
 * Friendly persona hint per scenario key, so the picker can read "Normal
 * employee — Bob Novak" without an extra round-trip to resolve the principal.
 * The API still returns the authoritative `actorName` for the transcript.
 */
const PERSONA_NAME: Record<string, string> = {
  "normal-employee": "Bob Novak",
  "contractor-guest": "Dev Patel",
};

interface ActorOption {
  /** The sentinel for the default persona, or a real actorPrincipalId. */
  value: string;
  label: string;
}

/** One turn in the running transcript. */
interface Turn {
  id: number;
  prompt: string;
  /** Resolved once the answer arrives. */
  answer?: CopilotAnswer;
  loading: boolean;
  error?: string;
}

/** A thin sensitivity bar, 0..1 mapped to a width + severity tint. */
function SensitivityBar({ value }: { value: number }) {
  const pct = Math.round(Math.min(1, Math.max(0, value)) * 100);
  const tint =
    value >= 0.9
      ? "bg-severity-critical"
      : value >= 0.6
        ? "bg-severity-high"
        : value >= 0.3
          ? "bg-severity-medium"
          : "bg-severity-low";
  return (
    <div className="flex items-center gap-2">
      <div className="h-2 w-28 overflow-hidden rounded-full bg-surface-muted">
        <div className={`h-full rounded-full ${tint}`} style={{ width: `${pct}%` }} aria-hidden />
      </div>
      <span className="w-9 text-right text-xs tabular-nums text-ink-soft">{value.toFixed(2)}</span>
    </div>
  );
}

function CopilotResponse({ answer }: { answer: CopilotAnswer }) {
  return (
    <div className="rounded-lg border border-surface-border bg-surface p-4">
      <div className="mb-2 flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-ink-faint">
        <span aria-hidden className="grid h-5 w-5 place-items-center rounded-full bg-brand/10 text-[10px] font-semibold text-brand">
          C
        </span>
        Copilot · grounded on {answer.actorName}&apos;s access
      </div>
      <p className="text-sm leading-relaxed text-ink">{answer.answer}</p>

      {answer.exposed ? (
        <div className="mt-3 rounded-md border border-severity-critical/30 bg-severity-critical/5 p-3">
          <p className="flex items-center gap-1.5 text-xs font-semibold text-severity-critical">
            <span aria-hidden>
              <AlertIcon size={13} />
            </span>
            {answer.citations.length} sensitive document
            {answer.citations.length === 1 ? "" : "s"} this user can reach
          </p>
          <ul className="mt-3 space-y-2">
            {answer.citations.map((c) => (
              <li key={c.resourceId} className="rounded-md border border-surface-border bg-surface p-3">
                <div className="flex items-start justify-between gap-3">
                  <div className="min-w-0">
                    <div className="truncate text-sm font-medium text-ink">{c.name}</div>
                    <div className="mt-0.5 text-xs text-ink-soft">
                      reachable via{" "}
                      <span className="rounded bg-surface-muted px-1.5 py-0.5 text-ink-soft">{c.via}</span>
                    </div>
                  </div>
                  <SensitivityBar value={c.sensitivity} />
                </div>
              </li>
            ))}
          </ul>
        </div>
      ) : (
        <div className="mt-3 rounded-md border border-severity-low/30 bg-severity-low/5 p-3 text-xs font-medium text-severity-low">
          Nothing exposed — Copilot would surface no sensitive documents this user can reach.
        </div>
      )}
    </div>
  );
}

export default function CopilotSimPage() {
  const { dataVersion, runAssessment, scanning } = useWorkspace();
  const [actor, setActor] = useState<string>(DEFAULT_ACTOR);
  const [draft, setDraft] = useState("");
  const [turns, setTurns] = useState<Turn[]>([]);
  const [nextId, setNextId] = useState(1);
  const [pending, setPending] = useState(false);
  /** Set when the very first ask reveals there is no connection yet. */
  const [noConnection, setNoConnection] = useState(false);

  // Scenarios give us selectable actor personas (those with an actorPrincipalId).
  const { data: scenarios } = useAsync<Scenario[]>(() => api.listScenarios(), [dataVersion]);

  const actorOptions = useMemo<ActorOption[]>(() => {
    const seen = new Set<string>();
    const opts: ActorOption[] = [{ value: DEFAULT_ACTOR, label: "Normal employee — Bob Novak (default)" }];
    for (const s of scenarios ?? []) {
      const pid = s.actorPrincipalId;
      if (!pid || seen.has(pid)) continue;
      seen.add(pid);
      // Skip the normal-employee persona — it's already the labeled default.
      if (s.key === "normal-employee") continue;
      const name = PERSONA_NAME[s.key];
      opts.push({ value: pid, label: name ? `${s.title} — ${name}` : s.title });
    }
    return opts;
  }, [scenarios]);

  const ask = async (prompt: string) => {
    const trimmed = prompt.trim();
    if (!trimmed || pending) return;
    const id = nextId;
    setNextId((n) => n + 1);
    setDraft("");
    setPending(true);
    setTurns((prev) => [...prev, { id, prompt: trimmed, loading: true }]);

    try {
      const answer = await api.copilotSim(trimmed, actor === DEFAULT_ACTOR ? undefined : actor);
      setTurns((prev) => prev.map((t) => (t.id === id ? { ...t, answer, loading: false } : t)));
    } catch (err) {
      if (err instanceof ApiError && err.status === 404) {
        // No connection yet — drop the optimistic turn and show the seed CTA.
        setTurns((prev) => prev.filter((t) => t.id !== id));
        setNoConnection(true);
      } else {
        const message = err instanceof Error ? err.message : "Copilot simulation failed.";
        setTurns((prev) => prev.map((t) => (t.id === id ? { ...t, error: message, loading: false } : t)));
      }
    } finally {
      setPending(false);
    }
  };

  const fieldClass =
    "rounded-md border border-surface-border bg-surface px-2.5 py-1.5 text-sm text-ink focus:outline-none focus:ring-2 focus:ring-brand/30";

  if (noConnection) {
    return (
      <>
        <PageHeader
          title="Copilot simulation"
          description="Ask as one of your users. See what Microsoft 365 Copilot, grounded on their access, would surface — and what's exposed."
        />
        <EmptyState
          title="No tenant connected yet"
          description="Run an exposure assessment to seed the demo tenant, then ask what Copilot would surface."
          action={
            <Button
              onClick={() => {
                void runAssessment().then(() => setNoConnection(false));
              }}
              busy={scanning}
            >
              Run exposure assessment
            </Button>
          }
        />
      </>
    );
  }

  return (
    <>
      <PageHeader
        title="Copilot simulation"
        description="Ask as one of your users. See what Microsoft 365 Copilot, grounded on their access, would surface — and what's exposed."
        actions={
          <label className="flex items-center gap-2 text-xs font-medium text-ink-soft">
            Ask as
            <select className={fieldClass} value={actor} onChange={(e) => setActor(e.target.value)}>
              {actorOptions.map((opt) => (
                <option key={opt.value} value={opt.value}>
                  {opt.label}
                </option>
              ))}
            </select>
          </label>
        }
      />

      <div className="space-y-5">
        <form
          onSubmit={(e) => {
            e.preventDefault();
            void ask(draft);
          }}
          className="rounded-lg border border-surface-border bg-surface p-4"
        >
          <div className="flex items-center gap-2">
            <input
              type="text"
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              placeholder="Ask Copilot something this user might ask…"
              className={`flex-1 ${fieldClass}`}
              aria-label="Prompt for Copilot"
            />
            <Button type="submit" busy={pending} disabled={draft.trim().length === 0}>
              Ask
            </Button>
          </div>
          <div className="mt-3 flex flex-wrap gap-2">
            {SUGGESTIONS.map((s) => (
              <button
                key={s}
                type="button"
                onClick={() => void ask(s)}
                disabled={pending}
                className="rounded-full border border-surface-border bg-surface-subtle px-3 py-1 text-xs text-ink-soft transition-colors hover:bg-surface-muted disabled:cursor-not-allowed disabled:opacity-50"
              >
                {s}
              </button>
            ))}
          </div>
        </form>

        {turns.length === 0 ? (
          <EmptyState
            title="Ask what Copilot would surface"
            description="Pick a persona above, then type a question or tap a suggestion. The answer is simulated from this user's access — deterministically, with no document content read."
          />
        ) : (
          <div className="space-y-4">
            {[...turns].reverse().map((turn) => (
              <div key={turn.id} className="space-y-2">
                <div className="flex justify-end">
                  <div className="max-w-[80%] rounded-lg rounded-br-sm bg-brand px-3.5 py-2 text-sm text-white">
                    {turn.prompt}
                  </div>
                </div>
                {turn.loading ? (
                  <div className="flex items-center gap-2 rounded-lg border border-surface-border bg-surface px-4 py-4 text-sm text-ink-soft">
                    <span
                      aria-hidden
                      className="h-4 w-4 animate-spin rounded-full border-2 border-surface-border border-t-brand"
                    />
                    Copilot is checking what this user can reach…
                  </div>
                ) : turn.error ? (
                  <ErrorState message={turn.error} onRetry={() => void ask(turn.prompt)} />
                ) : turn.answer ? (
                  <CopilotResponse answer={turn.answer} />
                ) : null}
              </div>
            ))}
          </div>
        )}

        <TrustCopy lines={SIM_TRUST} />
      </div>
    </>
  );
}
