import type { Band, EvidenceItem, Finding, RemediationTask, ScanResult, Scenario, Workspace } from "@cel/types";

export interface ReportFinding {
  finding: Finding;
  evidence: EvidenceItem[];
  remediation?: RemediationTask;
}

export interface ReportModel {
  title: string;
  workspaceName: string;
  generatedAt: string;
  scopeText: string;
  total: number;
  bandCounts: Record<Band, number>;
  findings: ReportFinding[];
  criticalAndHigh: ReportFinding[];
  resolved: ReportFinding[];
  scenarioRuns: { title: string; summary: string }[];
  methodology: string[];
  limitations: string[];
  dataHandling: string[];
  /**
   * Optional, env-gated AI narrative. Never affects scoring or findings — purely
   * a summary of the already-computed counts/titles. Unset by default.
   */
  llmSummary?: string;
}

const BANDS: Band[] = ["critical", "high", "medium", "low", "info"];

export interface BuildReportInput {
  workspace: Pick<Workspace, "name">;
  scanResult: ScanResult;
  scenarios: Scenario[];
}

/** Assemble a deterministic report model from a scan result. No LLM, no time. */
export function buildReportModel(input: BuildReportInput): ReportModel {
  const { scanResult, scenarios } = input;
  const evidenceByFinding = new Map<string, EvidenceItem[]>();
  for (const e of scanResult.evidence) {
    const list = evidenceByFinding.get(e.findingId) ?? [];
    list.push(e);
    evidenceByFinding.set(e.findingId, list);
  }
  const remediationById = new Map(scanResult.remediationTasks.map((t) => [t.id, t]));

  const findings: ReportFinding[] = scanResult.findings.map((finding) => ({
    finding,
    evidence: evidenceByFinding.get(finding.id) ?? [],
    remediation: finding.remediationTaskId ? remediationById.get(finding.remediationTaskId) : undefined,
  }));

  const bandCounts = Object.fromEntries(BANDS.map((b) => [b, 0])) as Record<Band, number>;
  for (const f of scanResult.findings) bandCounts[f.risk.band] += 1;

  const scenarioTitle = (id: string): string => scenarios.find((s) => s.id === id)?.title ?? id;

  return {
    title: "Copilot Exposure Assessment Report",
    workspaceName: input.workspace.name,
    generatedAt: scanResult.generatedAt,
    scopeText: "Microsoft 365 SharePoint / OneDrive permissions, sharing links, and Copilot Studio agents (metadata only).",
    total: scanResult.findings.length,
    bandCounts,
    findings,
    criticalAndHigh: findings.filter((f) => f.finding.risk.band === "critical" || f.finding.risk.band === "high"),
    resolved: findings.filter((f) => f.finding.status === "resolved"),
    scenarioRuns: scanResult.scenarioRuns.map((r) => ({ title: scenarioTitle(r.scenarioId), summary: r.summary })),
    methodology: [
      "Metadata ingestion of users, groups, sites, drives, files, permissions, sharing links, and agents.",
      "Permission-graph construction (group expansion, inheritance, links, guests, org-wide access).",
      "Deterministic exposure scenarios executed against the graph.",
      "Deterministic 0-100 risk scoring — severity is computed, never generated by an LLM.",
    ],
    limitations: [
      "Metadata-only mode may miss content-sensitive issues inside documents.",
      "Findings depend on the approved scan scope.",
      "This product does not guarantee Copilot safety; it surfaces and prioritizes exposure paths.",
    ],
    dataHandling: [
      "Document contents, email bodies, and credentials are not stored.",
      "Only metadata, permission grants, findings, evidence references, and reports are retained.",
      "Workspace deletion removes all associated data.",
    ],
  };
}
