/**
 * Hand-authored OpenAPI 3 description of the Copilot Exposure Lab REST API.
 *
 * It is the single source of truth served at GET /openapi.json and rendered by the
 * Swagger UI at GET /docs. Kept deliberately concise: full path + parameter
 * coverage (the part an integrator needs), generic response bodies (the shapes are
 * documented by @cel/types). Update this when routes change.
 */

const WS_PARAM = { $ref: "#/components/parameters/WorkspaceId" };
const FINDING_PARAM = { $ref: "#/components/parameters/FindingId" };
const LIMIT = { $ref: "#/components/parameters/Limit" };
const OFFSET = { $ref: "#/components/parameters/Offset" };

const ok = (description: string) => ({ "200": { description } });
const created = (description: string) => ({ "201": { description } });

export function buildOpenApiDocument(): Record<string, unknown> {
  return {
    openapi: "3.0.3",
    info: {
      title: "Copilot Exposure Lab API",
      version: "1.0.0",
      description:
        "Deterministic, metadata-only assessment of Microsoft 365 Copilot / Copilot Studio / SharePoint-OneDrive exposure. Severity is computed by a transparent 0–100 model — never generated by an LLM.",
      license: { name: "Proprietary" },
    },
    servers: [{ url: "/", description: "This API" }],
    tags: [
      { name: "System", description: "Health + documentation" },
      { name: "Workspaces", description: "Workspace lifecycle" },
      { name: "Connections", description: "Connect/seed a tenant (metadata-only)" },
      { name: "Assessment", description: "Scans, exposure score, graph, scenarios" },
      { name: "Findings", description: "Findings, evidence, remediation, fix scripts" },
      { name: "Threat", description: "MITRE ATT&CK / control mapping" },
      { name: "Reports", description: "Board-grade reports + exports" },
      { name: "Schedules", description: "Recurring scans/reports" },
    ],
    components: {
      securitySchemes: {
        bearerAuth: { type: "http", scheme: "bearer", description: "API key (only when auth is enabled)." },
      },
      parameters: {
        WorkspaceId: { name: "id", in: "path", required: true, schema: { type: "string" }, description: "Workspace id." },
        FindingId: { name: "fid", in: "path", required: true, schema: { type: "string" }, description: "Finding id." },
        Limit: { name: "limit", in: "query", required: false, schema: { type: "integer", minimum: 0 }, description: "Max items to return (omit for all)." },
        Offset: { name: "offset", in: "query", required: false, schema: { type: "integer", minimum: 0 }, description: "Items to skip." },
      },
    },
    paths: {
      "/health": { get: { tags: ["System"], summary: "Liveness probe", security: [], responses: ok("Service is up") } },
      "/openapi.json": { get: { tags: ["System"], summary: "This OpenAPI document", security: [], responses: ok("OpenAPI 3 spec") } },

      "/api/workspaces/{id}": {
        get: { tags: ["Workspaces"], summary: "Get a workspace", parameters: [WS_PARAM], responses: ok("Workspace") },
        delete: { tags: ["Workspaces"], summary: "Delete a workspace and all its data", parameters: [WS_PARAM], responses: { "204": { description: "Deleted" } } },
      },

      "/api/workspaces/{id}/connections/demo/seed": {
        post: { tags: ["Connections"], summary: "Seed the bundled demo tenant", parameters: [WS_PARAM], responses: created("Connection + counts") },
      },
      "/api/workspaces/{id}/connections/{system}/seed": {
        post: {
          tags: ["Connections"],
          summary: "Seed another system (google-workspace, slack, salesforce, multi-system, large-demo)",
          parameters: [WS_PARAM, { name: "system", in: "path", required: true, schema: { type: "string" } }],
          responses: created("Connection + counts"),
        },
      },
      "/api/workspaces/{id}/connections/microsoft/start": {
        post: { tags: ["Connections"], summary: "Connect a live M365 tenant (metadata-only; secret never stored)", parameters: [WS_PARAM], responses: created("Connection + counts") },
      },

      "/api/workspaces/{id}/scans": {
        post: { tags: ["Assessment"], summary: "Run a deterministic exposure scan", parameters: [WS_PARAM], responses: created("Scan run summary") },
      },
      "/api/workspaces/{id}/exposure": {
        get: { tags: ["Assessment"], summary: "Headline tenant exposure score (+ peer percentile)", parameters: [WS_PARAM], responses: ok("TenantExposure") },
      },
      "/api/workspaces/{id}/graph": {
        get: { tags: ["Assessment"], summary: "Exposure graph (union of every finding's path)", parameters: [WS_PARAM], responses: ok("ExposureGraphModel") },
      },
      "/api/workspaces/{id}/scenarios": {
        get: { tags: ["Assessment"], summary: "List scenario lenses", parameters: [WS_PARAM], responses: ok("Scenario[]") },
      },
      "/api/workspaces/{id}/resources": {
        get: { tags: ["Assessment"], summary: "List resources", parameters: [WS_PARAM, LIMIT, OFFSET], responses: ok("Resource[] (X-Total-Count header)") },
      },
      "/api/workspaces/{id}/retrieval": {
        get: { tags: ["Assessment"], summary: "What Copilot could surface to an actor", parameters: [WS_PARAM], responses: ok("RetrievalResult") },
      },
      "/api/workspaces/{id}/copilot-sim": {
        post: { tags: ["Assessment"], summary: "Simulate a Copilot answer (deterministic, no LLM)", parameters: [WS_PARAM], responses: ok("CopilotAnswer") },
      },

      "/api/workspaces/{id}/findings": {
        get: {
          tags: ["Findings"],
          summary: "List findings (filter + paginate)",
          parameters: [
            WS_PARAM,
            { name: "severity", in: "query", schema: { type: "string" } },
            { name: "status", in: "query", schema: { type: "string" } },
            { name: "scenarioId", in: "query", schema: { type: "string" } },
            LIMIT,
            OFFSET,
          ],
          responses: ok("Finding[] (X-Total-Count header)"),
        },
      },
      "/api/workspaces/{id}/findings/{fid}": {
        get: { tags: ["Findings"], summary: "Finding detail (evidence, remediation, sensitivity explanation)", parameters: [WS_PARAM, FINDING_PARAM], responses: ok("FindingDetail") },
        patch: { tags: ["Findings"], summary: "Update finding status / apply fix & re-verify", parameters: [WS_PARAM, FINDING_PARAM], responses: ok("Finding") },
      },
      "/api/workspaces/{id}/findings/{fid}/fix-script": {
        get: { tags: ["Findings"], summary: "Exact advisory Microsoft fix script (never executed)", parameters: [WS_PARAM, FINDING_PARAM], responses: ok("FixScript") },
      },

      "/api/workspaces/{id}/threat-model": {
        get: { tags: ["Threat"], summary: "Rules × MITRE ATT&CK × controls matrix", parameters: [WS_PARAM], responses: ok("ThreatModel") },
      },

      "/api/workspaces/{id}/reports": {
        post: { tags: ["Reports"], summary: "Generate a board-grade report (markdown/html)", parameters: [WS_PARAM], responses: created("Report") },
      },
      "/api/workspaces/{id}/exports": {
        get: { tags: ["Reports"], summary: "List available export formats", parameters: [WS_PARAM], responses: ok("ExportFormatInfo[]") },
      },
      "/api/workspaces/{id}/audit-events": {
        get: { tags: ["Reports"], summary: "Audit log (paginated)", parameters: [WS_PARAM, LIMIT, OFFSET], responses: ok("AuditEvent[] (X-Total-Count header)") },
      },

      "/api/workspaces/{id}/schedules": {
        get: { tags: ["Schedules"], summary: "List schedules", parameters: [WS_PARAM], responses: ok("Schedule[]") },
        post: { tags: ["Schedules"], summary: "Create a recurring scan/report schedule", parameters: [WS_PARAM], responses: created("Schedule") },
      },
    },
    security: [{ bearerAuth: [] }],
  };
}

/** Self-contained Swagger UI page (loads swagger-ui-dist from a CDN, points at /openapi.json). */
export const SWAGGER_UI_HTML = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Copilot Exposure Lab — API reference</title>
    <link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5.17.14/swagger-ui.css" />
    <style>body{margin:0}.topbar{display:none}</style>
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="https://unpkg.com/swagger-ui-dist@5.17.14/swagger-ui-bundle.js" crossorigin></script>
    <script>
      window.ui = SwaggerUIBundle({ url: "/openapi.json", dom_id: "#swagger-ui", deepLinking: true });
    </script>
  </body>
</html>`;
